package zdfs.model;

import java.util.Date;

public class AppointmentT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.p_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Integer p_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.d_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Integer d_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.tel
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.info
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.appoint_date
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Date appoint_date;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.appoint_time_start
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Date appoint_time_start;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.appoint_time_end
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Date appoint_time_end;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.state
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Integer state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.refuse_reason
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Integer refuse_reason;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.create_time
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.delflag
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Boolean delflag=false;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_t.embark_direction
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Boolean embark_direction;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.id
     *
     * @return the value of appointment_t.id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.id
     *
     * @param id the value for appointment_t.id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.p_id
     *
     * @return the value of appointment_t.p_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Integer getP_id() {
        return p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.p_id
     *
     * @param p_id the value for appointment_t.p_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setP_id(Integer p_id) {
        this.p_id = p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.d_id
     *
     * @return the value of appointment_t.d_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Integer getD_id() {
        return d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.d_id
     *
     * @param d_id the value for appointment_t.d_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setD_id(Integer d_id) {
        this.d_id = d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.tel
     *
     * @return the value of appointment_t.tel
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.tel
     *
     * @param tel the value for appointment_t.tel
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.info
     *
     * @return the value of appointment_t.info
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.info
     *
     * @param info the value for appointment_t.info
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.appoint_date
     *
     * @return the value of appointment_t.appoint_date
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Date getAppoint_date() {
        return appoint_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.appoint_date
     *
     * @param appoint_date the value for appointment_t.appoint_date
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setAppoint_date(Date appoint_date) {
        this.appoint_date = appoint_date;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.appoint_time_start
     *
     * @return the value of appointment_t.appoint_time_start
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Date getAppoint_time_start() {
        return appoint_time_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.appoint_time_start
     *
     * @param appoint_time_start the value for appointment_t.appoint_time_start
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setAppoint_time_start(Date appoint_time_start) {
        this.appoint_time_start = appoint_time_start;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.appoint_time_end
     *
     * @return the value of appointment_t.appoint_time_end
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Date getAppoint_time_end() {
        return appoint_time_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.appoint_time_end
     *
     * @param appoint_time_end the value for appointment_t.appoint_time_end
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setAppoint_time_end(Date appoint_time_end) {
        this.appoint_time_end = appoint_time_end;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.state
     *
     * @return the value of appointment_t.state
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.state
     *
     * @param state the value for appointment_t.state
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.refuse_reason
     *
     * @return the value of appointment_t.refuse_reason
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Integer getRefuse_reason() {
        return refuse_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.refuse_reason
     *
     * @param refuse_reason the value for appointment_t.refuse_reason
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setRefuse_reason(Integer refuse_reason) {
        this.refuse_reason = refuse_reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.create_time
     *
     * @return the value of appointment_t.create_time
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.create_time
     *
     * @param create_time the value for appointment_t.create_time
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.delflag
     *
     * @return the value of appointment_t.delflag
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.delflag
     *
     * @param delflag the value for appointment_t.delflag
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_t.embark_direction
     *
     * @return the value of appointment_t.embark_direction
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Boolean getEmbark_direction() {
        return embark_direction;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_t.embark_direction
     *
     * @param embark_direction the value for appointment_t.embark_direction
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setEmbark_direction(Boolean embark_direction) {
        this.embark_direction = embark_direction;
    }

	public AppointmentT(Integer p_id, Integer d_id, String tel, String info, Date appoint_date, Date appoint_time_start,
			Date appoint_time_end, Integer state, Integer refuse_reason, Boolean embark_direction) {
		super();
		this.p_id = p_id;
		this.d_id = d_id;
		this.tel = tel;
		this.info = info;
		this.appoint_date = appoint_date;
		this.appoint_time_start = appoint_time_start;
		this.appoint_time_end = appoint_time_end;
		this.state = state;
		this.refuse_reason = refuse_reason;
		this.embark_direction = embark_direction;
	}

	public AppointmentT() {
		super();
	}
    
    
}