package zdfs.model;

import java.util.Date;

public class DiagnoseT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnose_t.id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnose_t.p_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Integer p_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnose_t.tel
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnose_t.info
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String info;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnose_t.state
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Boolean state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnose_t.video
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnose_t.create_time
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnose_t.delflag
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Boolean delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column diagnose_t.d_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Integer d_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnose_t.id
     *
     * @return the value of diagnose_t.id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnose_t.id
     *
     * @param id the value for diagnose_t.id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnose_t.p_id
     *
     * @return the value of diagnose_t.p_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Integer getP_id() {
        return p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnose_t.p_id
     *
     * @param p_id the value for diagnose_t.p_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_id(Integer p_id) {
        this.p_id = p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnose_t.tel
     *
     * @return the value of diagnose_t.tel
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnose_t.tel
     *
     * @param tel the value for diagnose_t.tel
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnose_t.info
     *
     * @return the value of diagnose_t.info
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getInfo() {
        return info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnose_t.info
     *
     * @param info the value for diagnose_t.info
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setInfo(String info) {
        this.info = info;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnose_t.state
     *
     * @return the value of diagnose_t.state
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Boolean getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnose_t.state
     *
     * @param state the value for diagnose_t.state
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setState(Boolean state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnose_t.video
     *
     * @return the value of diagnose_t.video
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getVideo() {
        return video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnose_t.video
     *
     * @param video the value for diagnose_t.video
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setVideo(String video) {
        this.video = video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnose_t.create_time
     *
     * @return the value of diagnose_t.create_time
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnose_t.create_time
     *
     * @param create_time the value for diagnose_t.create_time
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnose_t.delflag
     *
     * @return the value of diagnose_t.delflag
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnose_t.delflag
     *
     * @param delflag the value for diagnose_t.delflag
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column diagnose_t.d_id
     *
     * @return the value of diagnose_t.d_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Integer getD_id() {
        return d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column diagnose_t.d_id
     *
     * @param d_id the value for diagnose_t.d_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setD_id(Integer d_id) {
        this.d_id = d_id;
    }
}