package zdfs.model;

import java.util.Date;

public class DoctorT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.id
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.name
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private String name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.pwd
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private String pwd;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.mail
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private String mail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.tel
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.photo
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private String photo;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.birthday
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.hospital
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private String hospital;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.department
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private String department;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.job
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.good_at
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private String good_at;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.online_state
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private Boolean online_state;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.has_video
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private Boolean has_video;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.create_time
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private Date create_time;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column doctor_t.login_time
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    private Date login_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.id
     *
     * @return the value of doctor_t.id
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.id
     *
     * @param id the value for doctor_t.id
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.name
     *
     * @return the value of doctor_t.name
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.name
     *
     * @param name the value for doctor_t.name
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setName(String name) {
        this.name = name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.pwd
     *
     * @return the value of doctor_t.pwd
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public String getPwd() {
        return pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.pwd
     *
     * @param pwd the value for doctor_t.pwd
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setPwd(String pwd) {
        this.pwd = pwd;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.mail
     *
     * @return the value of doctor_t.mail
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public String getMail() {
        return mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.mail
     *
     * @param mail the value for doctor_t.mail
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setMail(String mail) {
        this.mail = mail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.tel
     *
     * @return the value of doctor_t.tel
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.tel
     *
     * @param tel the value for doctor_t.tel
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.photo
     *
     * @return the value of doctor_t.photo
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public String getPhoto() {
        return photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.photo
     *
     * @param photo the value for doctor_t.photo
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setPhoto(String photo) {
        this.photo = photo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.birthday
     *
     * @return the value of doctor_t.birthday
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.birthday
     *
     * @param birthday the value for doctor_t.birthday
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.hospital
     *
     * @return the value of doctor_t.hospital
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public String getHospital() {
        return hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.hospital
     *
     * @param hospital the value for doctor_t.hospital
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setHospital(String hospital) {
        this.hospital = hospital;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.department
     *
     * @return the value of doctor_t.department
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public String getDepartment() {
        return department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.department
     *
     * @param department the value for doctor_t.department
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setDepartment(String department) {
        this.department = department;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.job
     *
     * @return the value of doctor_t.job
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.job
     *
     * @param job the value for doctor_t.job
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.good_at
     *
     * @return the value of doctor_t.good_at
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public String getGood_at() {
        return good_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.good_at
     *
     * @param good_at the value for doctor_t.good_at
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setGood_at(String good_at) {
        this.good_at = good_at;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.online_state
     *
     * @return the value of doctor_t.online_state
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public Boolean getOnline_state() {
        return online_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.online_state
     *
     * @param online_state the value for doctor_t.online_state
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setOnline_state(Boolean online_state) {
        this.online_state = online_state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.has_video
     *
     * @return the value of doctor_t.has_video
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public Boolean getHas_video() {
        return has_video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.has_video
     *
     * @param has_video the value for doctor_t.has_video
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setHas_video(Boolean has_video) {
        this.has_video = has_video;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.create_time
     *
     * @return the value of doctor_t.create_time
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.create_time
     *
     * @param create_time the value for doctor_t.create_time
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column doctor_t.login_time
     *
     * @return the value of doctor_t.login_time
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public Date getLogin_time() {
        return login_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column doctor_t.login_time
     *
     * @param login_time the value for doctor_t.login_time
     *
     * @mbg.generated Thu Jul 13 20:33:13 CST 2017
     */
    public void setLogin_time(Date login_time) {
        this.login_time = login_time;
    }
}