package zdfs.model;

public class PatientT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_id
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    private Integer p_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_name
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    private String p_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_sex
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    private Boolean p_sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_age
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    private Integer p_age;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.member_id
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    private Integer member_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.d_id
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    private Integer d_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.delflag
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    private Boolean delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_id
     *
     * @return the value of patient_t.p_id
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public Integer getP_id() {
        return p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_id
     *
     * @param p_id the value for patient_t.p_id
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public void setP_id(Integer p_id) {
        this.p_id = p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_name
     *
     * @return the value of patient_t.p_name
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public String getP_name() {
        return p_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_name
     *
     * @param p_name the value for patient_t.p_name
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public void setP_name(String p_name) {
        this.p_name = p_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_sex
     *
     * @return the value of patient_t.p_sex
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public Boolean getP_sex() {
        return p_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_sex
     *
     * @param p_sex the value for patient_t.p_sex
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public void setP_sex(Boolean p_sex) {
        this.p_sex = p_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_age
     *
     * @return the value of patient_t.p_age
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public Integer getP_age() {
        return p_age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_age
     *
     * @param p_age the value for patient_t.p_age
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public void setP_age(Integer p_age) {
        this.p_age = p_age;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.member_id
     *
     * @return the value of patient_t.member_id
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public Integer getMember_id() {
        return member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.member_id
     *
     * @param member_id the value for patient_t.member_id
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public void setMember_id(Integer member_id) {
        this.member_id = member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.d_id
     *
     * @return the value of patient_t.d_id
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public Integer getD_id() {
        return d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.d_id
     *
     * @param d_id the value for patient_t.d_id
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public void setD_id(Integer d_id) {
        this.d_id = d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.delflag
     *
     * @return the value of patient_t.delflag
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.delflag
     *
     * @param delflag the value for patient_t.delflag
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }
}