package zdfs.model;

import java.util.Date;

public class PatientT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Integer p_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_name
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_name;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_sex
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Boolean p_sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_birthday
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Date p_birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.member_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Integer member_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.d_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Integer d_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.delflag
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Boolean delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_tel
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_id_type
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_id_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_id_number
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_id_number;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_nickname
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_nickname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_picture
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_blood_type
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_blood_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_marry_status
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private Boolean p_marry_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_job
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_social_card
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_social_card;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_address
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column patient_t.p_home
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    private String p_home;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_id
     *
     * @return the value of patient_t.p_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Integer getP_id() {
        return p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_id
     *
     * @param p_id the value for patient_t.p_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_id(Integer p_id) {
        this.p_id = p_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_name
     *
     * @return the value of patient_t.p_name
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_name() {
        return p_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_name
     *
     * @param p_name the value for patient_t.p_name
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_name(String p_name) {
        this.p_name = p_name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_sex
     *
     * @return the value of patient_t.p_sex
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Boolean getP_sex() {
        return p_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_sex
     *
     * @param p_sex the value for patient_t.p_sex
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_sex(Boolean p_sex) {
        this.p_sex = p_sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_birthday
     *
     * @return the value of patient_t.p_birthday
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Date getP_birthday() {
        return p_birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_birthday
     *
     * @param p_birthday the value for patient_t.p_birthday
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_birthday(Date p_birthday) {
        this.p_birthday = p_birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.member_id
     *
     * @return the value of patient_t.member_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Integer getMember_id() {
        return member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.member_id
     *
     * @param member_id the value for patient_t.member_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setMember_id(Integer member_id) {
        this.member_id = member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.d_id
     *
     * @return the value of patient_t.d_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Integer getD_id() {
        return d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.d_id
     *
     * @param d_id the value for patient_t.d_id
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setD_id(Integer d_id) {
        this.d_id = d_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.delflag
     *
     * @return the value of patient_t.delflag
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.delflag
     *
     * @param delflag the value for patient_t.delflag
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_tel
     *
     * @return the value of patient_t.p_tel
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_tel() {
        return p_tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_tel
     *
     * @param p_tel the value for patient_t.p_tel
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_tel(String p_tel) {
        this.p_tel = p_tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_id_type
     *
     * @return the value of patient_t.p_id_type
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_id_type() {
        return p_id_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_id_type
     *
     * @param p_id_type the value for patient_t.p_id_type
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_id_type(String p_id_type) {
        this.p_id_type = p_id_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_id_number
     *
     * @return the value of patient_t.p_id_number
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_id_number() {
        return p_id_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_id_number
     *
     * @param p_id_number the value for patient_t.p_id_number
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_id_number(String p_id_number) {
        this.p_id_number = p_id_number;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_nickname
     *
     * @return the value of patient_t.p_nickname
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_nickname() {
        return p_nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_nickname
     *
     * @param p_nickname the value for patient_t.p_nickname
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_nickname(String p_nickname) {
        this.p_nickname = p_nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_picture
     *
     * @return the value of patient_t.p_picture
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_picture() {
        return p_picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_picture
     *
     * @param p_picture the value for patient_t.p_picture
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_picture(String p_picture) {
        this.p_picture = p_picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_blood_type
     *
     * @return the value of patient_t.p_blood_type
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_blood_type() {
        return p_blood_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_blood_type
     *
     * @param p_blood_type the value for patient_t.p_blood_type
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_blood_type(String p_blood_type) {
        this.p_blood_type = p_blood_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_marry_status
     *
     * @return the value of patient_t.p_marry_status
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Boolean getP_marry_status() {
        return p_marry_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_marry_status
     *
     * @param p_marry_status the value for patient_t.p_marry_status
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_marry_status(Boolean p_marry_status) {
        this.p_marry_status = p_marry_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_job
     *
     * @return the value of patient_t.p_job
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_job() {
        return p_job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_job
     *
     * @param p_job the value for patient_t.p_job
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_job(String p_job) {
        this.p_job = p_job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_social_card
     *
     * @return the value of patient_t.p_social_card
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_social_card() {
        return p_social_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_social_card
     *
     * @param p_social_card the value for patient_t.p_social_card
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_social_card(String p_social_card) {
        this.p_social_card = p_social_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_address
     *
     * @return the value of patient_t.p_address
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_address() {
        return p_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_address
     *
     * @param p_address the value for patient_t.p_address
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_address(String p_address) {
        this.p_address = p_address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column patient_t.p_home
     *
     * @return the value of patient_t.p_home
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getP_home() {
        return p_home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column patient_t.p_home
     *
     * @param p_home the value for patient_t.p_home
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setP_home(String p_home) {
        this.p_home = p_home;
    }

	public PatientT(String p_name, Boolean p_sex, Date p_birthday, Integer member_id, Integer d_id, String p_tel,
			String p_id_type, String p_id_number, String p_nickname, String p_picture, String p_blood_type,
			Boolean p_marry_status, String p_job, String p_social_card, String p_address, String p_home) {
		super();
		this.p_name = p_name;
		this.p_sex = p_sex;
		this.p_birthday = p_birthday;
		this.member_id = member_id;
		this.d_id = d_id;
		this.p_tel = p_tel;
		this.p_id_type = p_id_type;
		this.p_id_number = p_id_number;
		this.p_nickname = p_nickname;
		this.p_picture = p_picture;
		this.p_blood_type = p_blood_type;
		this.p_marry_status = p_marry_status;
		this.p_job = p_job;
		this.p_social_card = p_social_card;
		this.p_address = p_address;
		this.p_home = p_home;
	}
}