package zdfs.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class PatientTExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public PatientTExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andP_idIsNull() {
            addCriterion("p_id is null");
            return (Criteria) this;
        }

        public Criteria andP_idIsNotNull() {
            addCriterion("p_id is not null");
            return (Criteria) this;
        }

        public Criteria andP_idEqualTo(Integer value) {
            addCriterion("p_id =", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idNotEqualTo(Integer value) {
            addCriterion("p_id <>", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idGreaterThan(Integer value) {
            addCriterion("p_id >", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("p_id >=", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idLessThan(Integer value) {
            addCriterion("p_id <", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idLessThanOrEqualTo(Integer value) {
            addCriterion("p_id <=", value, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idIn(List<Integer> values) {
            addCriterion("p_id in", values, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idNotIn(List<Integer> values) {
            addCriterion("p_id not in", values, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idBetween(Integer value1, Integer value2) {
            addCriterion("p_id between", value1, value2, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_idNotBetween(Integer value1, Integer value2) {
            addCriterion("p_id not between", value1, value2, "p_id");
            return (Criteria) this;
        }

        public Criteria andP_nameIsNull() {
            addCriterion("p_name is null");
            return (Criteria) this;
        }

        public Criteria andP_nameIsNotNull() {
            addCriterion("p_name is not null");
            return (Criteria) this;
        }

        public Criteria andP_nameEqualTo(String value) {
            addCriterion("p_name =", value, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameNotEqualTo(String value) {
            addCriterion("p_name <>", value, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameGreaterThan(String value) {
            addCriterion("p_name >", value, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameGreaterThanOrEqualTo(String value) {
            addCriterion("p_name >=", value, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameLessThan(String value) {
            addCriterion("p_name <", value, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameLessThanOrEqualTo(String value) {
            addCriterion("p_name <=", value, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameLike(String value) {
            addCriterion("p_name like", value, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameNotLike(String value) {
            addCriterion("p_name not like", value, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameIn(List<String> values) {
            addCriterion("p_name in", values, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameNotIn(List<String> values) {
            addCriterion("p_name not in", values, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameBetween(String value1, String value2) {
            addCriterion("p_name between", value1, value2, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_nameNotBetween(String value1, String value2) {
            addCriterion("p_name not between", value1, value2, "p_name");
            return (Criteria) this;
        }

        public Criteria andP_sexIsNull() {
            addCriterion("p_sex is null");
            return (Criteria) this;
        }

        public Criteria andP_sexIsNotNull() {
            addCriterion("p_sex is not null");
            return (Criteria) this;
        }

        public Criteria andP_sexEqualTo(Boolean value) {
            addCriterion("p_sex =", value, "p_sex");
            return (Criteria) this;
        }

        public Criteria andP_sexNotEqualTo(Boolean value) {
            addCriterion("p_sex <>", value, "p_sex");
            return (Criteria) this;
        }

        public Criteria andP_sexGreaterThan(Boolean value) {
            addCriterion("p_sex >", value, "p_sex");
            return (Criteria) this;
        }

        public Criteria andP_sexGreaterThanOrEqualTo(Boolean value) {
            addCriterion("p_sex >=", value, "p_sex");
            return (Criteria) this;
        }

        public Criteria andP_sexLessThan(Boolean value) {
            addCriterion("p_sex <", value, "p_sex");
            return (Criteria) this;
        }

        public Criteria andP_sexLessThanOrEqualTo(Boolean value) {
            addCriterion("p_sex <=", value, "p_sex");
            return (Criteria) this;
        }

        public Criteria andP_sexIn(List<Boolean> values) {
            addCriterion("p_sex in", values, "p_sex");
            return (Criteria) this;
        }

        public Criteria andP_sexNotIn(List<Boolean> values) {
            addCriterion("p_sex not in", values, "p_sex");
            return (Criteria) this;
        }

        public Criteria andP_sexBetween(Boolean value1, Boolean value2) {
            addCriterion("p_sex between", value1, value2, "p_sex");
            return (Criteria) this;
        }

        public Criteria andP_sexNotBetween(Boolean value1, Boolean value2) {
            addCriterion("p_sex not between", value1, value2, "p_sex");
            return (Criteria) this;
        }

        public Criteria andP_birthdayIsNull() {
            addCriterion("p_birthday is null");
            return (Criteria) this;
        }

        public Criteria andP_birthdayIsNotNull() {
            addCriterion("p_birthday is not null");
            return (Criteria) this;
        }

        public Criteria andP_birthdayEqualTo(Date value) {
            addCriterionForJDBCDate("p_birthday =", value, "p_birthday");
            return (Criteria) this;
        }

        public Criteria andP_birthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("p_birthday <>", value, "p_birthday");
            return (Criteria) this;
        }

        public Criteria andP_birthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("p_birthday >", value, "p_birthday");
            return (Criteria) this;
        }

        public Criteria andP_birthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("p_birthday >=", value, "p_birthday");
            return (Criteria) this;
        }

        public Criteria andP_birthdayLessThan(Date value) {
            addCriterionForJDBCDate("p_birthday <", value, "p_birthday");
            return (Criteria) this;
        }

        public Criteria andP_birthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("p_birthday <=", value, "p_birthday");
            return (Criteria) this;
        }

        public Criteria andP_birthdayIn(List<Date> values) {
            addCriterionForJDBCDate("p_birthday in", values, "p_birthday");
            return (Criteria) this;
        }

        public Criteria andP_birthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("p_birthday not in", values, "p_birthday");
            return (Criteria) this;
        }

        public Criteria andP_birthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("p_birthday between", value1, value2, "p_birthday");
            return (Criteria) this;
        }

        public Criteria andP_birthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("p_birthday not between", value1, value2, "p_birthday");
            return (Criteria) this;
        }

        public Criteria andMember_idIsNull() {
            addCriterion("member_id is null");
            return (Criteria) this;
        }

        public Criteria andMember_idIsNotNull() {
            addCriterion("member_id is not null");
            return (Criteria) this;
        }

        public Criteria andMember_idEqualTo(Integer value) {
            addCriterion("member_id =", value, "member_id");
            return (Criteria) this;
        }

        public Criteria andMember_idNotEqualTo(Integer value) {
            addCriterion("member_id <>", value, "member_id");
            return (Criteria) this;
        }

        public Criteria andMember_idGreaterThan(Integer value) {
            addCriterion("member_id >", value, "member_id");
            return (Criteria) this;
        }

        public Criteria andMember_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("member_id >=", value, "member_id");
            return (Criteria) this;
        }

        public Criteria andMember_idLessThan(Integer value) {
            addCriterion("member_id <", value, "member_id");
            return (Criteria) this;
        }

        public Criteria andMember_idLessThanOrEqualTo(Integer value) {
            addCriterion("member_id <=", value, "member_id");
            return (Criteria) this;
        }

        public Criteria andMember_idIn(List<Integer> values) {
            addCriterion("member_id in", values, "member_id");
            return (Criteria) this;
        }

        public Criteria andMember_idNotIn(List<Integer> values) {
            addCriterion("member_id not in", values, "member_id");
            return (Criteria) this;
        }

        public Criteria andMember_idBetween(Integer value1, Integer value2) {
            addCriterion("member_id between", value1, value2, "member_id");
            return (Criteria) this;
        }

        public Criteria andMember_idNotBetween(Integer value1, Integer value2) {
            addCriterion("member_id not between", value1, value2, "member_id");
            return (Criteria) this;
        }

        public Criteria andD_idIsNull() {
            addCriterion("d_id is null");
            return (Criteria) this;
        }

        public Criteria andD_idIsNotNull() {
            addCriterion("d_id is not null");
            return (Criteria) this;
        }

        public Criteria andD_idEqualTo(Integer value) {
            addCriterion("d_id =", value, "d_id");
            return (Criteria) this;
        }

        public Criteria andD_idNotEqualTo(Integer value) {
            addCriterion("d_id <>", value, "d_id");
            return (Criteria) this;
        }

        public Criteria andD_idGreaterThan(Integer value) {
            addCriterion("d_id >", value, "d_id");
            return (Criteria) this;
        }

        public Criteria andD_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("d_id >=", value, "d_id");
            return (Criteria) this;
        }

        public Criteria andD_idLessThan(Integer value) {
            addCriterion("d_id <", value, "d_id");
            return (Criteria) this;
        }

        public Criteria andD_idLessThanOrEqualTo(Integer value) {
            addCriterion("d_id <=", value, "d_id");
            return (Criteria) this;
        }

        public Criteria andD_idIn(List<Integer> values) {
            addCriterion("d_id in", values, "d_id");
            return (Criteria) this;
        }

        public Criteria andD_idNotIn(List<Integer> values) {
            addCriterion("d_id not in", values, "d_id");
            return (Criteria) this;
        }

        public Criteria andD_idBetween(Integer value1, Integer value2) {
            addCriterion("d_id between", value1, value2, "d_id");
            return (Criteria) this;
        }

        public Criteria andD_idNotBetween(Integer value1, Integer value2) {
            addCriterion("d_id not between", value1, value2, "d_id");
            return (Criteria) this;
        }

        public Criteria andDelflagIsNull() {
            addCriterion("delflag is null");
            return (Criteria) this;
        }

        public Criteria andDelflagIsNotNull() {
            addCriterion("delflag is not null");
            return (Criteria) this;
        }

        public Criteria andDelflagEqualTo(Boolean value) {
            addCriterion("delflag =", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotEqualTo(Boolean value) {
            addCriterion("delflag <>", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagGreaterThan(Boolean value) {
            addCriterion("delflag >", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delflag >=", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagLessThan(Boolean value) {
            addCriterion("delflag <", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagLessThanOrEqualTo(Boolean value) {
            addCriterion("delflag <=", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagIn(List<Boolean> values) {
            addCriterion("delflag in", values, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotIn(List<Boolean> values) {
            addCriterion("delflag not in", values, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagBetween(Boolean value1, Boolean value2) {
            addCriterion("delflag between", value1, value2, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delflag not between", value1, value2, "delflag");
            return (Criteria) this;
        }

        public Criteria andP_telIsNull() {
            addCriterion("p_tel is null");
            return (Criteria) this;
        }

        public Criteria andP_telIsNotNull() {
            addCriterion("p_tel is not null");
            return (Criteria) this;
        }

        public Criteria andP_telEqualTo(String value) {
            addCriterion("p_tel =", value, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telNotEqualTo(String value) {
            addCriterion("p_tel <>", value, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telGreaterThan(String value) {
            addCriterion("p_tel >", value, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telGreaterThanOrEqualTo(String value) {
            addCriterion("p_tel >=", value, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telLessThan(String value) {
            addCriterion("p_tel <", value, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telLessThanOrEqualTo(String value) {
            addCriterion("p_tel <=", value, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telLike(String value) {
            addCriterion("p_tel like", value, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telNotLike(String value) {
            addCriterion("p_tel not like", value, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telIn(List<String> values) {
            addCriterion("p_tel in", values, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telNotIn(List<String> values) {
            addCriterion("p_tel not in", values, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telBetween(String value1, String value2) {
            addCriterion("p_tel between", value1, value2, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_telNotBetween(String value1, String value2) {
            addCriterion("p_tel not between", value1, value2, "p_tel");
            return (Criteria) this;
        }

        public Criteria andP_id_typeIsNull() {
            addCriterion("p_id_type is null");
            return (Criteria) this;
        }

        public Criteria andP_id_typeIsNotNull() {
            addCriterion("p_id_type is not null");
            return (Criteria) this;
        }

        public Criteria andP_id_typeEqualTo(String value) {
            addCriterion("p_id_type =", value, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeNotEqualTo(String value) {
            addCriterion("p_id_type <>", value, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeGreaterThan(String value) {
            addCriterion("p_id_type >", value, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeGreaterThanOrEqualTo(String value) {
            addCriterion("p_id_type >=", value, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeLessThan(String value) {
            addCriterion("p_id_type <", value, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeLessThanOrEqualTo(String value) {
            addCriterion("p_id_type <=", value, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeLike(String value) {
            addCriterion("p_id_type like", value, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeNotLike(String value) {
            addCriterion("p_id_type not like", value, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeIn(List<String> values) {
            addCriterion("p_id_type in", values, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeNotIn(List<String> values) {
            addCriterion("p_id_type not in", values, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeBetween(String value1, String value2) {
            addCriterion("p_id_type between", value1, value2, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_typeNotBetween(String value1, String value2) {
            addCriterion("p_id_type not between", value1, value2, "p_id_type");
            return (Criteria) this;
        }

        public Criteria andP_id_numberIsNull() {
            addCriterion("p_id_number is null");
            return (Criteria) this;
        }

        public Criteria andP_id_numberIsNotNull() {
            addCriterion("p_id_number is not null");
            return (Criteria) this;
        }

        public Criteria andP_id_numberEqualTo(String value) {
            addCriterion("p_id_number =", value, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberNotEqualTo(String value) {
            addCriterion("p_id_number <>", value, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberGreaterThan(String value) {
            addCriterion("p_id_number >", value, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberGreaterThanOrEqualTo(String value) {
            addCriterion("p_id_number >=", value, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberLessThan(String value) {
            addCriterion("p_id_number <", value, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberLessThanOrEqualTo(String value) {
            addCriterion("p_id_number <=", value, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberLike(String value) {
            addCriterion("p_id_number like", value, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberNotLike(String value) {
            addCriterion("p_id_number not like", value, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberIn(List<String> values) {
            addCriterion("p_id_number in", values, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberNotIn(List<String> values) {
            addCriterion("p_id_number not in", values, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberBetween(String value1, String value2) {
            addCriterion("p_id_number between", value1, value2, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_id_numberNotBetween(String value1, String value2) {
            addCriterion("p_id_number not between", value1, value2, "p_id_number");
            return (Criteria) this;
        }

        public Criteria andP_nicknameIsNull() {
            addCriterion("p_nickname is null");
            return (Criteria) this;
        }

        public Criteria andP_nicknameIsNotNull() {
            addCriterion("p_nickname is not null");
            return (Criteria) this;
        }

        public Criteria andP_nicknameEqualTo(String value) {
            addCriterion("p_nickname =", value, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameNotEqualTo(String value) {
            addCriterion("p_nickname <>", value, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameGreaterThan(String value) {
            addCriterion("p_nickname >", value, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameGreaterThanOrEqualTo(String value) {
            addCriterion("p_nickname >=", value, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameLessThan(String value) {
            addCriterion("p_nickname <", value, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameLessThanOrEqualTo(String value) {
            addCriterion("p_nickname <=", value, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameLike(String value) {
            addCriterion("p_nickname like", value, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameNotLike(String value) {
            addCriterion("p_nickname not like", value, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameIn(List<String> values) {
            addCriterion("p_nickname in", values, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameNotIn(List<String> values) {
            addCriterion("p_nickname not in", values, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameBetween(String value1, String value2) {
            addCriterion("p_nickname between", value1, value2, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_nicknameNotBetween(String value1, String value2) {
            addCriterion("p_nickname not between", value1, value2, "p_nickname");
            return (Criteria) this;
        }

        public Criteria andP_pictureIsNull() {
            addCriterion("p_picture is null");
            return (Criteria) this;
        }

        public Criteria andP_pictureIsNotNull() {
            addCriterion("p_picture is not null");
            return (Criteria) this;
        }

        public Criteria andP_pictureEqualTo(String value) {
            addCriterion("p_picture =", value, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureNotEqualTo(String value) {
            addCriterion("p_picture <>", value, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureGreaterThan(String value) {
            addCriterion("p_picture >", value, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureGreaterThanOrEqualTo(String value) {
            addCriterion("p_picture >=", value, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureLessThan(String value) {
            addCriterion("p_picture <", value, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureLessThanOrEqualTo(String value) {
            addCriterion("p_picture <=", value, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureLike(String value) {
            addCriterion("p_picture like", value, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureNotLike(String value) {
            addCriterion("p_picture not like", value, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureIn(List<String> values) {
            addCriterion("p_picture in", values, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureNotIn(List<String> values) {
            addCriterion("p_picture not in", values, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureBetween(String value1, String value2) {
            addCriterion("p_picture between", value1, value2, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_pictureNotBetween(String value1, String value2) {
            addCriterion("p_picture not between", value1, value2, "p_picture");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeIsNull() {
            addCriterion("p_blood_type is null");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeIsNotNull() {
            addCriterion("p_blood_type is not null");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeEqualTo(String value) {
            addCriterion("p_blood_type =", value, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeNotEqualTo(String value) {
            addCriterion("p_blood_type <>", value, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeGreaterThan(String value) {
            addCriterion("p_blood_type >", value, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeGreaterThanOrEqualTo(String value) {
            addCriterion("p_blood_type >=", value, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeLessThan(String value) {
            addCriterion("p_blood_type <", value, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeLessThanOrEqualTo(String value) {
            addCriterion("p_blood_type <=", value, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeLike(String value) {
            addCriterion("p_blood_type like", value, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeNotLike(String value) {
            addCriterion("p_blood_type not like", value, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeIn(List<String> values) {
            addCriterion("p_blood_type in", values, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeNotIn(List<String> values) {
            addCriterion("p_blood_type not in", values, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeBetween(String value1, String value2) {
            addCriterion("p_blood_type between", value1, value2, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_blood_typeNotBetween(String value1, String value2) {
            addCriterion("p_blood_type not between", value1, value2, "p_blood_type");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusIsNull() {
            addCriterion("p_marry_status is null");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusIsNotNull() {
            addCriterion("p_marry_status is not null");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusEqualTo(Boolean value) {
            addCriterion("p_marry_status =", value, "p_marry_status");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusNotEqualTo(Boolean value) {
            addCriterion("p_marry_status <>", value, "p_marry_status");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusGreaterThan(Boolean value) {
            addCriterion("p_marry_status >", value, "p_marry_status");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusGreaterThanOrEqualTo(Boolean value) {
            addCriterion("p_marry_status >=", value, "p_marry_status");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusLessThan(Boolean value) {
            addCriterion("p_marry_status <", value, "p_marry_status");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusLessThanOrEqualTo(Boolean value) {
            addCriterion("p_marry_status <=", value, "p_marry_status");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusIn(List<Boolean> values) {
            addCriterion("p_marry_status in", values, "p_marry_status");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusNotIn(List<Boolean> values) {
            addCriterion("p_marry_status not in", values, "p_marry_status");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusBetween(Boolean value1, Boolean value2) {
            addCriterion("p_marry_status between", value1, value2, "p_marry_status");
            return (Criteria) this;
        }

        public Criteria andP_marry_statusNotBetween(Boolean value1, Boolean value2) {
            addCriterion("p_marry_status not between", value1, value2, "p_marry_status");
            return (Criteria) this;
        }

        public Criteria andP_jobIsNull() {
            addCriterion("p_job is null");
            return (Criteria) this;
        }

        public Criteria andP_jobIsNotNull() {
            addCriterion("p_job is not null");
            return (Criteria) this;
        }

        public Criteria andP_jobEqualTo(String value) {
            addCriterion("p_job =", value, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobNotEqualTo(String value) {
            addCriterion("p_job <>", value, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobGreaterThan(String value) {
            addCriterion("p_job >", value, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobGreaterThanOrEqualTo(String value) {
            addCriterion("p_job >=", value, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobLessThan(String value) {
            addCriterion("p_job <", value, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobLessThanOrEqualTo(String value) {
            addCriterion("p_job <=", value, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobLike(String value) {
            addCriterion("p_job like", value, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobNotLike(String value) {
            addCriterion("p_job not like", value, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobIn(List<String> values) {
            addCriterion("p_job in", values, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobNotIn(List<String> values) {
            addCriterion("p_job not in", values, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobBetween(String value1, String value2) {
            addCriterion("p_job between", value1, value2, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_jobNotBetween(String value1, String value2) {
            addCriterion("p_job not between", value1, value2, "p_job");
            return (Criteria) this;
        }

        public Criteria andP_social_cardIsNull() {
            addCriterion("p_social_card is null");
            return (Criteria) this;
        }

        public Criteria andP_social_cardIsNotNull() {
            addCriterion("p_social_card is not null");
            return (Criteria) this;
        }

        public Criteria andP_social_cardEqualTo(String value) {
            addCriterion("p_social_card =", value, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardNotEqualTo(String value) {
            addCriterion("p_social_card <>", value, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardGreaterThan(String value) {
            addCriterion("p_social_card >", value, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardGreaterThanOrEqualTo(String value) {
            addCriterion("p_social_card >=", value, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardLessThan(String value) {
            addCriterion("p_social_card <", value, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardLessThanOrEqualTo(String value) {
            addCriterion("p_social_card <=", value, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardLike(String value) {
            addCriterion("p_social_card like", value, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardNotLike(String value) {
            addCriterion("p_social_card not like", value, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardIn(List<String> values) {
            addCriterion("p_social_card in", values, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardNotIn(List<String> values) {
            addCriterion("p_social_card not in", values, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardBetween(String value1, String value2) {
            addCriterion("p_social_card between", value1, value2, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_social_cardNotBetween(String value1, String value2) {
            addCriterion("p_social_card not between", value1, value2, "p_social_card");
            return (Criteria) this;
        }

        public Criteria andP_addressIsNull() {
            addCriterion("p_address is null");
            return (Criteria) this;
        }

        public Criteria andP_addressIsNotNull() {
            addCriterion("p_address is not null");
            return (Criteria) this;
        }

        public Criteria andP_addressEqualTo(String value) {
            addCriterion("p_address =", value, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressNotEqualTo(String value) {
            addCriterion("p_address <>", value, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressGreaterThan(String value) {
            addCriterion("p_address >", value, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressGreaterThanOrEqualTo(String value) {
            addCriterion("p_address >=", value, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressLessThan(String value) {
            addCriterion("p_address <", value, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressLessThanOrEqualTo(String value) {
            addCriterion("p_address <=", value, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressLike(String value) {
            addCriterion("p_address like", value, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressNotLike(String value) {
            addCriterion("p_address not like", value, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressIn(List<String> values) {
            addCriterion("p_address in", values, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressNotIn(List<String> values) {
            addCriterion("p_address not in", values, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressBetween(String value1, String value2) {
            addCriterion("p_address between", value1, value2, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_addressNotBetween(String value1, String value2) {
            addCriterion("p_address not between", value1, value2, "p_address");
            return (Criteria) this;
        }

        public Criteria andP_homeIsNull() {
            addCriterion("p_home is null");
            return (Criteria) this;
        }

        public Criteria andP_homeIsNotNull() {
            addCriterion("p_home is not null");
            return (Criteria) this;
        }

        public Criteria andP_homeEqualTo(String value) {
            addCriterion("p_home =", value, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeNotEqualTo(String value) {
            addCriterion("p_home <>", value, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeGreaterThan(String value) {
            addCriterion("p_home >", value, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeGreaterThanOrEqualTo(String value) {
            addCriterion("p_home >=", value, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeLessThan(String value) {
            addCriterion("p_home <", value, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeLessThanOrEqualTo(String value) {
            addCriterion("p_home <=", value, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeLike(String value) {
            addCriterion("p_home like", value, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeNotLike(String value) {
            addCriterion("p_home not like", value, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeIn(List<String> values) {
            addCriterion("p_home in", values, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeNotIn(List<String> values) {
            addCriterion("p_home not in", values, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeBetween(String value1, String value2) {
            addCriterion("p_home between", value1, value2, "p_home");
            return (Criteria) this;
        }

        public Criteria andP_homeNotBetween(String value1, String value2) {
            addCriterion("p_home not between", value1, value2, "p_home");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_t
     *
     * @mbg.generated do_not_delete_during_merge Fri Jul 21 10:18:19 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table patient_t
     *
     * @mbg.generated Fri Jul 21 10:18:19 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}