package zdfs.model;

import java.util.Date;

public class RDoctorAnychatT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_doctor_anychat_t.doc_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Integer doc_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_doctor_anychat_t.anychat_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Integer anychat_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_doctor_anychat_t.delflag
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Boolean delflag=false;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_doctor_anychat_t.create_time
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_doctor_anychat_t.doc_id
     *
     * @return the value of r_doctor_anychat_t.doc_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Integer getDoc_id() {
        return doc_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_doctor_anychat_t.doc_id
     *
     * @param doc_id the value for r_doctor_anychat_t.doc_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setDoc_id(Integer doc_id) {
        this.doc_id = doc_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_doctor_anychat_t.anychat_id
     *
     * @return the value of r_doctor_anychat_t.anychat_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Integer getAnychat_id() {
        return anychat_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_doctor_anychat_t.anychat_id
     *
     * @param anychat_id the value for r_doctor_anychat_t.anychat_id
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setAnychat_id(Integer anychat_id) {
        this.anychat_id = anychat_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_doctor_anychat_t.delflag
     *
     * @return the value of r_doctor_anychat_t.delflag
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_doctor_anychat_t.delflag
     *
     * @param delflag the value for r_doctor_anychat_t.delflag
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_doctor_anychat_t.create_time
     *
     * @return the value of r_doctor_anychat_t.create_time
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_doctor_anychat_t.create_time
     *
     * @param create_time the value for r_doctor_anychat_t.create_time
     *
     * @mbg.generated Mon Jul 17 20:14:02 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

	public RDoctorAnychatT(Integer doc_id, Integer anychat_id) {
		super();
		this.doc_id = doc_id;
		this.anychat_id = anychat_id;
	}

	public RDoctorAnychatT() {
		super();
	}
	
	
}