package zdfs.model;

public class RDoctorPatientsT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_doctor_patients_t.did
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    private Integer did;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_doctor_patients_t.pid
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    private Integer pid;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_doctor_patients_t.did
     *
     * @return the value of r_doctor_patients_t.did
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    public Integer getDid() {
        return did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_doctor_patients_t.did
     *
     * @param did the value for r_doctor_patients_t.did
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    public void setDid(Integer did) {
        this.did = did;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_doctor_patients_t.pid
     *
     * @return the value of r_doctor_patients_t.pid
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_doctor_patients_t.pid
     *
     * @param pid the value for r_doctor_patients_t.pid
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }
}