package zdfs.model;

import java.util.Date;

public class RDoctorAnychatT {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_doctor_anychat_t.doctor_id
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    private Integer doctor_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_doctor_anychat_t.anychat_id
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    private Integer anychat_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_doctor_anychat_t.delflag
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    private Boolean delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column r_doctor_anychat_t.create_time
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    private Date create_time;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_doctor_anychat_t.doctor_id
     *
     * @return the value of r_doctor_anychat_t.doctor_id
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    public Integer getDoctor_id() {
        return doctor_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_doctor_anychat_t.doctor_id
     *
     * @param doctor_id the value for r_doctor_anychat_t.doctor_id
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    public void setDoctor_id(Integer doctor_id) {
        this.doctor_id = doctor_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_doctor_anychat_t.anychat_id
     *
     * @return the value of r_doctor_anychat_t.anychat_id
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    public Integer getAnychat_id() {
        return anychat_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_doctor_anychat_t.anychat_id
     *
     * @param anychat_id the value for r_doctor_anychat_t.anychat_id
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    public void setAnychat_id(Integer anychat_id) {
        this.anychat_id = anychat_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_doctor_anychat_t.delflag
     *
     * @return the value of r_doctor_anychat_t.delflag
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_doctor_anychat_t.delflag
     *
     * @param delflag the value for r_doctor_anychat_t.delflag
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column r_doctor_anychat_t.create_time
     *
     * @return the value of r_doctor_anychat_t.create_time
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    public Date getCreate_time() {
        return create_time;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column r_doctor_anychat_t.create_time
     *
     * @param create_time the value for r_doctor_anychat_t.create_time
     *
     * @mbg.generated Fri Jul 21 10:07:34 CST 2017
     */
    public void setCreate_time(Date create_time) {
        this.create_time = create_time;
    }

}