package zdfs.tf02.model;

import java.util.Date;

public class BfData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.member_id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String member_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.pid
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.meatime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Date meatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.physicalstate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Integer physicalstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.bf_weight
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Float bf_weight;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.bf_fat_rate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Float bf_fat_rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.bf_muscle_rate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Float bf_muscle_rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.bf_water_rate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Float bf_water_rate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.healthrecord
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String healthrecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.createtime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bf_data.delflag
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Boolean delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.id
     *
     * @return the value of bf_data.id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.id
     *
     * @param id the value for bf_data.id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.member_id
     *
     * @return the value of bf_data.member_id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getMember_id() {
        return member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.member_id
     *
     * @param member_id the value for bf_data.member_id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setMember_id(String member_id) {
        this.member_id = member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.pid
     *
     * @return the value of bf_data.pid
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.pid
     *
     * @param pid the value for bf_data.pid
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.meatime
     *
     * @return the value of bf_data.meatime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Date getMeatime() {
        return meatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.meatime
     *
     * @param meatime the value for bf_data.meatime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setMeatime(Date meatime) {
        this.meatime = meatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.physicalstate
     *
     * @return the value of bf_data.physicalstate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Integer getPhysicalstate() {
        return physicalstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.physicalstate
     *
     * @param physicalstate the value for bf_data.physicalstate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setPhysicalstate(Integer physicalstate) {
        this.physicalstate = physicalstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.bf_weight
     *
     * @return the value of bf_data.bf_weight
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Float getBf_weight() {
        return bf_weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.bf_weight
     *
     * @param bf_weight the value for bf_data.bf_weight
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setBf_weight(Float bf_weight) {
        this.bf_weight = bf_weight;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.bf_fat_rate
     *
     * @return the value of bf_data.bf_fat_rate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Float getBf_fat_rate() {
        return bf_fat_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.bf_fat_rate
     *
     * @param bf_fat_rate the value for bf_data.bf_fat_rate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setBf_fat_rate(Float bf_fat_rate) {
        this.bf_fat_rate = bf_fat_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.bf_muscle_rate
     *
     * @return the value of bf_data.bf_muscle_rate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Float getBf_muscle_rate() {
        return bf_muscle_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.bf_muscle_rate
     *
     * @param bf_muscle_rate the value for bf_data.bf_muscle_rate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setBf_muscle_rate(Float bf_muscle_rate) {
        this.bf_muscle_rate = bf_muscle_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.bf_water_rate
     *
     * @return the value of bf_data.bf_water_rate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Float getBf_water_rate() {
        return bf_water_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.bf_water_rate
     *
     * @param bf_water_rate the value for bf_data.bf_water_rate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setBf_water_rate(Float bf_water_rate) {
        this.bf_water_rate = bf_water_rate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.healthrecord
     *
     * @return the value of bf_data.healthrecord
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getHealthrecord() {
        return healthrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.healthrecord
     *
     * @param healthrecord the value for bf_data.healthrecord
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setHealthrecord(String healthrecord) {
        this.healthrecord = healthrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.createtime
     *
     * @return the value of bf_data.createtime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.createtime
     *
     * @param createtime the value for bf_data.createtime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bf_data.delflag
     *
     * @return the value of bf_data.delflag
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bf_data.delflag
     *
     * @param delflag the value for bf_data.delflag
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }
}