package zdfs.tf02.model;

import java.util.Date;

public class BpData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.id
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.member_id
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private String member_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.pid
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.meatime
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private Date meatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.physicalstate
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private Integer physicalstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.bp_sp
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private Integer bp_sp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.bp_dp
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private Integer bp_dp;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.bp_hr
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private Integer bp_hr;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.healthrecord
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private String healthrecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.createtime
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column bp_data.delflag
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    private Boolean delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.id
     *
     * @return the value of bp_data.id
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.id
     *
     * @param id the value for bp_data.id
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.member_id
     *
     * @return the value of bp_data.member_id
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public String getMember_id() {
        return member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.member_id
     *
     * @param member_id the value for bp_data.member_id
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setMember_id(String member_id) {
        this.member_id = member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.pid
     *
     * @return the value of bp_data.pid
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.pid
     *
     * @param pid the value for bp_data.pid
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.meatime
     *
     * @return the value of bp_data.meatime
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public Date getMeatime() {
        return meatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.meatime
     *
     * @param meatime the value for bp_data.meatime
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setMeatime(Date meatime) {
        this.meatime = meatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.physicalstate
     *
     * @return the value of bp_data.physicalstate
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public Integer getPhysicalstate() {
        return physicalstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.physicalstate
     *
     * @param physicalstate the value for bp_data.physicalstate
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setPhysicalstate(Integer physicalstate) {
        this.physicalstate = physicalstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.bp_sp
     *
     * @return the value of bp_data.bp_sp
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public Integer getBp_sp() {
        return bp_sp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.bp_sp
     *
     * @param bp_sp the value for bp_data.bp_sp
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setBp_sp(Integer bp_sp) {
        this.bp_sp = bp_sp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.bp_dp
     *
     * @return the value of bp_data.bp_dp
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public Integer getBp_dp() {
        return bp_dp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.bp_dp
     *
     * @param bp_dp the value for bp_data.bp_dp
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setBp_dp(Integer bp_dp) {
        this.bp_dp = bp_dp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.bp_hr
     *
     * @return the value of bp_data.bp_hr
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public Integer getBp_hr() {
        return bp_hr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.bp_hr
     *
     * @param bp_hr the value for bp_data.bp_hr
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setBp_hr(Integer bp_hr) {
        this.bp_hr = bp_hr;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.healthrecord
     *
     * @return the value of bp_data.healthrecord
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public String getHealthrecord() {
        return healthrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.healthrecord
     *
     * @param healthrecord the value for bp_data.healthrecord
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setHealthrecord(String healthrecord) {
        this.healthrecord = healthrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.createtime
     *
     * @return the value of bp_data.createtime
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.createtime
     *
     * @param createtime the value for bp_data.createtime
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column bp_data.delflag
     *
     * @return the value of bp_data.delflag
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column bp_data.delflag
     *
     * @param delflag the value for bp_data.delflag
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }
}