package zdfs.tf02.model;

import java.util.Date;

public class EcgData {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.member_id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String member_id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.pid
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String pid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.physicalstate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Integer physicalstate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.numberturns
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Integer numberturns;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.eegdata
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String eegdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.healthrecord
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String healthrecord;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.meatime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Date meatime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.ecgdata
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Integer ecgdata;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.createtime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ecg_data.delflag
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Boolean delflag;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.id
     *
     * @return the value of ecg_data.id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.id
     *
     * @param id the value for ecg_data.id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.member_id
     *
     * @return the value of ecg_data.member_id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getMember_id() {
        return member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.member_id
     *
     * @param member_id the value for ecg_data.member_id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setMember_id(String member_id) {
        this.member_id = member_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.pid
     *
     * @return the value of ecg_data.pid
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.pid
     *
     * @param pid the value for ecg_data.pid
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setPid(String pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.physicalstate
     *
     * @return the value of ecg_data.physicalstate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Integer getPhysicalstate() {
        return physicalstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.physicalstate
     *
     * @param physicalstate the value for ecg_data.physicalstate
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setPhysicalstate(Integer physicalstate) {
        this.physicalstate = physicalstate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.numberturns
     *
     * @return the value of ecg_data.numberturns
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Integer getNumberturns() {
        return numberturns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.numberturns
     *
     * @param numberturns the value for ecg_data.numberturns
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setNumberturns(Integer numberturns) {
        this.numberturns = numberturns;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.eegdata
     *
     * @return the value of ecg_data.eegdata
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getEegdata() {
        return eegdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.eegdata
     *
     * @param eegdata the value for ecg_data.eegdata
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setEegdata(String eegdata) {
        this.eegdata = eegdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.healthrecord
     *
     * @return the value of ecg_data.healthrecord
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getHealthrecord() {
        return healthrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.healthrecord
     *
     * @param healthrecord the value for ecg_data.healthrecord
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setHealthrecord(String healthrecord) {
        this.healthrecord = healthrecord;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.meatime
     *
     * @return the value of ecg_data.meatime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Date getMeatime() {
        return meatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.meatime
     *
     * @param meatime the value for ecg_data.meatime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setMeatime(Date meatime) {
        this.meatime = meatime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.ecgdata
     *
     * @return the value of ecg_data.ecgdata
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Integer getEcgdata() {
        return ecgdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.ecgdata
     *
     * @param ecgdata the value for ecg_data.ecgdata
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setEcgdata(Integer ecgdata) {
        this.ecgdata = ecgdata;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.createtime
     *
     * @return the value of ecg_data.createtime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.createtime
     *
     * @param createtime the value for ecg_data.createtime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ecg_data.delflag
     *
     * @return the value of ecg_data.delflag
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ecg_data.delflag
     *
     * @param delflag the value for ecg_data.delflag
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }
}