package zdfs.tf02.model;

import java.util.Date;

public class MembersInfo {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.membersname
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String membersname;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.sex
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Boolean sex;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.id_type
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String id_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.id_card
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String id_card;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.tel
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.picture
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String picture;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.blood_type
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String blood_type;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.marry_status
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String marry_status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.job
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String job;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.birthday
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Date birthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.social_card
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String social_card;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.address
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.home
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String home;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.height
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String height;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.history
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String history;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.allergic
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String allergic;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.family
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private String family;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.createtime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.delflag
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Boolean delflag;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column members_info.client_id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    private Integer client_id;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.id
     *
     * @return the value of members_info.id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.id
     *
     * @param id the value for members_info.id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.membersname
     *
     * @return the value of members_info.membersname
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getMembersname() {
        return membersname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.membersname
     *
     * @param membersname the value for members_info.membersname
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setMembersname(String membersname) {
        this.membersname = membersname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.sex
     *
     * @return the value of members_info.sex
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Boolean getSex() {
        return sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.sex
     *
     * @param sex the value for members_info.sex
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setSex(Boolean sex) {
        this.sex = sex;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.id_type
     *
     * @return the value of members_info.id_type
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getId_type() {
        return id_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.id_type
     *
     * @param id_type the value for members_info.id_type
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setId_type(String id_type) {
        this.id_type = id_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.id_card
     *
     * @return the value of members_info.id_card
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getId_card() {
        return id_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.id_card
     *
     * @param id_card the value for members_info.id_card
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setId_card(String id_card) {
        this.id_card = id_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.tel
     *
     * @return the value of members_info.tel
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.tel
     *
     * @param tel the value for members_info.tel
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setTel(String tel) {
        this.tel = tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.picture
     *
     * @return the value of members_info.picture
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getPicture() {
        return picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.picture
     *
     * @param picture the value for members_info.picture
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setPicture(String picture) {
        this.picture = picture;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.blood_type
     *
     * @return the value of members_info.blood_type
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getBlood_type() {
        return blood_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.blood_type
     *
     * @param blood_type the value for members_info.blood_type
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setBlood_type(String blood_type) {
        this.blood_type = blood_type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.marry_status
     *
     * @return the value of members_info.marry_status
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getMarry_status() {
        return marry_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.marry_status
     *
     * @param marry_status the value for members_info.marry_status
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setMarry_status(String marry_status) {
        this.marry_status = marry_status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.job
     *
     * @return the value of members_info.job
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getJob() {
        return job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.job
     *
     * @param job the value for members_info.job
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setJob(String job) {
        this.job = job;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.birthday
     *
     * @return the value of members_info.birthday
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Date getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.birthday
     *
     * @param birthday the value for members_info.birthday
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.social_card
     *
     * @return the value of members_info.social_card
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getSocial_card() {
        return social_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.social_card
     *
     * @param social_card the value for members_info.social_card
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setSocial_card(String social_card) {
        this.social_card = social_card;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.address
     *
     * @return the value of members_info.address
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.address
     *
     * @param address the value for members_info.address
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setAddress(String address) {
        this.address = address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.home
     *
     * @return the value of members_info.home
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getHome() {
        return home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.home
     *
     * @param home the value for members_info.home
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setHome(String home) {
        this.home = home;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.height
     *
     * @return the value of members_info.height
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getHeight() {
        return height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.height
     *
     * @param height the value for members_info.height
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setHeight(String height) {
        this.height = height;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.history
     *
     * @return the value of members_info.history
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getHistory() {
        return history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.history
     *
     * @param history the value for members_info.history
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setHistory(String history) {
        this.history = history;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.allergic
     *
     * @return the value of members_info.allergic
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getAllergic() {
        return allergic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.allergic
     *
     * @param allergic the value for members_info.allergic
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setAllergic(String allergic) {
        this.allergic = allergic;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.family
     *
     * @return the value of members_info.family
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getFamily() {
        return family;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.family
     *
     * @param family the value for members_info.family
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setFamily(String family) {
        this.family = family;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.createtime
     *
     * @return the value of members_info.createtime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.createtime
     *
     * @param createtime the value for members_info.createtime
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.delflag
     *
     * @return the value of members_info.delflag
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Boolean getDelflag() {
        return delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.delflag
     *
     * @param delflag the value for members_info.delflag
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setDelflag(Boolean delflag) {
        this.delflag = delflag;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column members_info.client_id
     *
     * @return the value of members_info.client_id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Integer getClient_id() {
        return client_id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column members_info.client_id
     *
     * @param client_id the value for members_info.client_id
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setClient_id(Integer client_id) {
        this.client_id = client_id;
    }
}