package zdfs.tf02.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.Iterator;
import java.util.List;

public class MembersInfoExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public MembersInfoExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        protected void addCriterionForJDBCDate(String condition, Date value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value.getTime()), property);
        }

        protected void addCriterionForJDBCDate(String condition, List<Date> values, String property) {
            if (values == null || values.size() == 0) {
                throw new RuntimeException("Value list for " + property + " cannot be null or empty");
            }
            List<java.sql.Date> dateList = new ArrayList<java.sql.Date>();
            Iterator<Date> iter = values.iterator();
            while (iter.hasNext()) {
                dateList.add(new java.sql.Date(iter.next().getTime()));
            }
            addCriterion(condition, dateList, property);
        }

        protected void addCriterionForJDBCDate(String condition, Date value1, Date value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            addCriterion(condition, new java.sql.Date(value1.getTime()), new java.sql.Date(value2.getTime()), property);
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Integer value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Integer value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Integer value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Integer value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Integer value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Integer> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Integer> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Integer value1, Integer value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Integer value1, Integer value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andMembersnameIsNull() {
            addCriterion("membersname is null");
            return (Criteria) this;
        }

        public Criteria andMembersnameIsNotNull() {
            addCriterion("membersname is not null");
            return (Criteria) this;
        }

        public Criteria andMembersnameEqualTo(String value) {
            addCriterion("membersname =", value, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameNotEqualTo(String value) {
            addCriterion("membersname <>", value, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameGreaterThan(String value) {
            addCriterion("membersname >", value, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameGreaterThanOrEqualTo(String value) {
            addCriterion("membersname >=", value, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameLessThan(String value) {
            addCriterion("membersname <", value, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameLessThanOrEqualTo(String value) {
            addCriterion("membersname <=", value, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameLike(String value) {
            addCriterion("membersname like", value, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameNotLike(String value) {
            addCriterion("membersname not like", value, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameIn(List<String> values) {
            addCriterion("membersname in", values, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameNotIn(List<String> values) {
            addCriterion("membersname not in", values, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameBetween(String value1, String value2) {
            addCriterion("membersname between", value1, value2, "membersname");
            return (Criteria) this;
        }

        public Criteria andMembersnameNotBetween(String value1, String value2) {
            addCriterion("membersname not between", value1, value2, "membersname");
            return (Criteria) this;
        }

        public Criteria andSexIsNull() {
            addCriterion("sex is null");
            return (Criteria) this;
        }

        public Criteria andSexIsNotNull() {
            addCriterion("sex is not null");
            return (Criteria) this;
        }

        public Criteria andSexEqualTo(Boolean value) {
            addCriterion("sex =", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotEqualTo(Boolean value) {
            addCriterion("sex <>", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThan(Boolean value) {
            addCriterion("sex >", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexGreaterThanOrEqualTo(Boolean value) {
            addCriterion("sex >=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThan(Boolean value) {
            addCriterion("sex <", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexLessThanOrEqualTo(Boolean value) {
            addCriterion("sex <=", value, "sex");
            return (Criteria) this;
        }

        public Criteria andSexIn(List<Boolean> values) {
            addCriterion("sex in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotIn(List<Boolean> values) {
            addCriterion("sex not in", values, "sex");
            return (Criteria) this;
        }

        public Criteria andSexBetween(Boolean value1, Boolean value2) {
            addCriterion("sex between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andSexNotBetween(Boolean value1, Boolean value2) {
            addCriterion("sex not between", value1, value2, "sex");
            return (Criteria) this;
        }

        public Criteria andId_typeIsNull() {
            addCriterion("id_type is null");
            return (Criteria) this;
        }

        public Criteria andId_typeIsNotNull() {
            addCriterion("id_type is not null");
            return (Criteria) this;
        }

        public Criteria andId_typeEqualTo(String value) {
            addCriterion("id_type =", value, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeNotEqualTo(String value) {
            addCriterion("id_type <>", value, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeGreaterThan(String value) {
            addCriterion("id_type >", value, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeGreaterThanOrEqualTo(String value) {
            addCriterion("id_type >=", value, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeLessThan(String value) {
            addCriterion("id_type <", value, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeLessThanOrEqualTo(String value) {
            addCriterion("id_type <=", value, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeLike(String value) {
            addCriterion("id_type like", value, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeNotLike(String value) {
            addCriterion("id_type not like", value, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeIn(List<String> values) {
            addCriterion("id_type in", values, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeNotIn(List<String> values) {
            addCriterion("id_type not in", values, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeBetween(String value1, String value2) {
            addCriterion("id_type between", value1, value2, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_typeNotBetween(String value1, String value2) {
            addCriterion("id_type not between", value1, value2, "id_type");
            return (Criteria) this;
        }

        public Criteria andId_cardIsNull() {
            addCriterion("id_card is null");
            return (Criteria) this;
        }

        public Criteria andId_cardIsNotNull() {
            addCriterion("id_card is not null");
            return (Criteria) this;
        }

        public Criteria andId_cardEqualTo(String value) {
            addCriterion("id_card =", value, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardNotEqualTo(String value) {
            addCriterion("id_card <>", value, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardGreaterThan(String value) {
            addCriterion("id_card >", value, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardGreaterThanOrEqualTo(String value) {
            addCriterion("id_card >=", value, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardLessThan(String value) {
            addCriterion("id_card <", value, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardLessThanOrEqualTo(String value) {
            addCriterion("id_card <=", value, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardLike(String value) {
            addCriterion("id_card like", value, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardNotLike(String value) {
            addCriterion("id_card not like", value, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardIn(List<String> values) {
            addCriterion("id_card in", values, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardNotIn(List<String> values) {
            addCriterion("id_card not in", values, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardBetween(String value1, String value2) {
            addCriterion("id_card between", value1, value2, "id_card");
            return (Criteria) this;
        }

        public Criteria andId_cardNotBetween(String value1, String value2) {
            addCriterion("id_card not between", value1, value2, "id_card");
            return (Criteria) this;
        }

        public Criteria andTelIsNull() {
            addCriterion("tel is null");
            return (Criteria) this;
        }

        public Criteria andTelIsNotNull() {
            addCriterion("tel is not null");
            return (Criteria) this;
        }

        public Criteria andTelEqualTo(String value) {
            addCriterion("tel =", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotEqualTo(String value) {
            addCriterion("tel <>", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThan(String value) {
            addCriterion("tel >", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelGreaterThanOrEqualTo(String value) {
            addCriterion("tel >=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThan(String value) {
            addCriterion("tel <", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLessThanOrEqualTo(String value) {
            addCriterion("tel <=", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelLike(String value) {
            addCriterion("tel like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotLike(String value) {
            addCriterion("tel not like", value, "tel");
            return (Criteria) this;
        }

        public Criteria andTelIn(List<String> values) {
            addCriterion("tel in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotIn(List<String> values) {
            addCriterion("tel not in", values, "tel");
            return (Criteria) this;
        }

        public Criteria andTelBetween(String value1, String value2) {
            addCriterion("tel between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andTelNotBetween(String value1, String value2) {
            addCriterion("tel not between", value1, value2, "tel");
            return (Criteria) this;
        }

        public Criteria andPictureIsNull() {
            addCriterion("picture is null");
            return (Criteria) this;
        }

        public Criteria andPictureIsNotNull() {
            addCriterion("picture is not null");
            return (Criteria) this;
        }

        public Criteria andPictureEqualTo(String value) {
            addCriterion("picture =", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotEqualTo(String value) {
            addCriterion("picture <>", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThan(String value) {
            addCriterion("picture >", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureGreaterThanOrEqualTo(String value) {
            addCriterion("picture >=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThan(String value) {
            addCriterion("picture <", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLessThanOrEqualTo(String value) {
            addCriterion("picture <=", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureLike(String value) {
            addCriterion("picture like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotLike(String value) {
            addCriterion("picture not like", value, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureIn(List<String> values) {
            addCriterion("picture in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotIn(List<String> values) {
            addCriterion("picture not in", values, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureBetween(String value1, String value2) {
            addCriterion("picture between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andPictureNotBetween(String value1, String value2) {
            addCriterion("picture not between", value1, value2, "picture");
            return (Criteria) this;
        }

        public Criteria andBlood_typeIsNull() {
            addCriterion("blood_type is null");
            return (Criteria) this;
        }

        public Criteria andBlood_typeIsNotNull() {
            addCriterion("blood_type is not null");
            return (Criteria) this;
        }

        public Criteria andBlood_typeEqualTo(String value) {
            addCriterion("blood_type =", value, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeNotEqualTo(String value) {
            addCriterion("blood_type <>", value, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeGreaterThan(String value) {
            addCriterion("blood_type >", value, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeGreaterThanOrEqualTo(String value) {
            addCriterion("blood_type >=", value, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeLessThan(String value) {
            addCriterion("blood_type <", value, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeLessThanOrEqualTo(String value) {
            addCriterion("blood_type <=", value, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeLike(String value) {
            addCriterion("blood_type like", value, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeNotLike(String value) {
            addCriterion("blood_type not like", value, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeIn(List<String> values) {
            addCriterion("blood_type in", values, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeNotIn(List<String> values) {
            addCriterion("blood_type not in", values, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeBetween(String value1, String value2) {
            addCriterion("blood_type between", value1, value2, "blood_type");
            return (Criteria) this;
        }

        public Criteria andBlood_typeNotBetween(String value1, String value2) {
            addCriterion("blood_type not between", value1, value2, "blood_type");
            return (Criteria) this;
        }

        public Criteria andMarry_statusIsNull() {
            addCriterion("marry_status is null");
            return (Criteria) this;
        }

        public Criteria andMarry_statusIsNotNull() {
            addCriterion("marry_status is not null");
            return (Criteria) this;
        }

        public Criteria andMarry_statusEqualTo(String value) {
            addCriterion("marry_status =", value, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusNotEqualTo(String value) {
            addCriterion("marry_status <>", value, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusGreaterThan(String value) {
            addCriterion("marry_status >", value, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusGreaterThanOrEqualTo(String value) {
            addCriterion("marry_status >=", value, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusLessThan(String value) {
            addCriterion("marry_status <", value, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusLessThanOrEqualTo(String value) {
            addCriterion("marry_status <=", value, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusLike(String value) {
            addCriterion("marry_status like", value, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusNotLike(String value) {
            addCriterion("marry_status not like", value, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusIn(List<String> values) {
            addCriterion("marry_status in", values, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusNotIn(List<String> values) {
            addCriterion("marry_status not in", values, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusBetween(String value1, String value2) {
            addCriterion("marry_status between", value1, value2, "marry_status");
            return (Criteria) this;
        }

        public Criteria andMarry_statusNotBetween(String value1, String value2) {
            addCriterion("marry_status not between", value1, value2, "marry_status");
            return (Criteria) this;
        }

        public Criteria andJobIsNull() {
            addCriterion("job is null");
            return (Criteria) this;
        }

        public Criteria andJobIsNotNull() {
            addCriterion("job is not null");
            return (Criteria) this;
        }

        public Criteria andJobEqualTo(String value) {
            addCriterion("job =", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobNotEqualTo(String value) {
            addCriterion("job <>", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobGreaterThan(String value) {
            addCriterion("job >", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobGreaterThanOrEqualTo(String value) {
            addCriterion("job >=", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobLessThan(String value) {
            addCriterion("job <", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobLessThanOrEqualTo(String value) {
            addCriterion("job <=", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobLike(String value) {
            addCriterion("job like", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobNotLike(String value) {
            addCriterion("job not like", value, "job");
            return (Criteria) this;
        }

        public Criteria andJobIn(List<String> values) {
            addCriterion("job in", values, "job");
            return (Criteria) this;
        }

        public Criteria andJobNotIn(List<String> values) {
            addCriterion("job not in", values, "job");
            return (Criteria) this;
        }

        public Criteria andJobBetween(String value1, String value2) {
            addCriterion("job between", value1, value2, "job");
            return (Criteria) this;
        }

        public Criteria andJobNotBetween(String value1, String value2) {
            addCriterion("job not between", value1, value2, "job");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNull() {
            addCriterion("birthday is null");
            return (Criteria) this;
        }

        public Criteria andBirthdayIsNotNull() {
            addCriterion("birthday is not null");
            return (Criteria) this;
        }

        public Criteria andBirthdayEqualTo(Date value) {
            addCriterionForJDBCDate("birthday =", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotEqualTo(Date value) {
            addCriterionForJDBCDate("birthday <>", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThan(Date value) {
            addCriterionForJDBCDate("birthday >", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayGreaterThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birthday >=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThan(Date value) {
            addCriterionForJDBCDate("birthday <", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayLessThanOrEqualTo(Date value) {
            addCriterionForJDBCDate("birthday <=", value, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayIn(List<Date> values) {
            addCriterionForJDBCDate("birthday in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotIn(List<Date> values) {
            addCriterionForJDBCDate("birthday not in", values, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birthday between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andBirthdayNotBetween(Date value1, Date value2) {
            addCriterionForJDBCDate("birthday not between", value1, value2, "birthday");
            return (Criteria) this;
        }

        public Criteria andSocial_cardIsNull() {
            addCriterion("social_card is null");
            return (Criteria) this;
        }

        public Criteria andSocial_cardIsNotNull() {
            addCriterion("social_card is not null");
            return (Criteria) this;
        }

        public Criteria andSocial_cardEqualTo(String value) {
            addCriterion("social_card =", value, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardNotEqualTo(String value) {
            addCriterion("social_card <>", value, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardGreaterThan(String value) {
            addCriterion("social_card >", value, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardGreaterThanOrEqualTo(String value) {
            addCriterion("social_card >=", value, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardLessThan(String value) {
            addCriterion("social_card <", value, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardLessThanOrEqualTo(String value) {
            addCriterion("social_card <=", value, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardLike(String value) {
            addCriterion("social_card like", value, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardNotLike(String value) {
            addCriterion("social_card not like", value, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardIn(List<String> values) {
            addCriterion("social_card in", values, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardNotIn(List<String> values) {
            addCriterion("social_card not in", values, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardBetween(String value1, String value2) {
            addCriterion("social_card between", value1, value2, "social_card");
            return (Criteria) this;
        }

        public Criteria andSocial_cardNotBetween(String value1, String value2) {
            addCriterion("social_card not between", value1, value2, "social_card");
            return (Criteria) this;
        }

        public Criteria andAddressIsNull() {
            addCriterion("address is null");
            return (Criteria) this;
        }

        public Criteria andAddressIsNotNull() {
            addCriterion("address is not null");
            return (Criteria) this;
        }

        public Criteria andAddressEqualTo(String value) {
            addCriterion("address =", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotEqualTo(String value) {
            addCriterion("address <>", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThan(String value) {
            addCriterion("address >", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressGreaterThanOrEqualTo(String value) {
            addCriterion("address >=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThan(String value) {
            addCriterion("address <", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLessThanOrEqualTo(String value) {
            addCriterion("address <=", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressLike(String value) {
            addCriterion("address like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotLike(String value) {
            addCriterion("address not like", value, "address");
            return (Criteria) this;
        }

        public Criteria andAddressIn(List<String> values) {
            addCriterion("address in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotIn(List<String> values) {
            addCriterion("address not in", values, "address");
            return (Criteria) this;
        }

        public Criteria andAddressBetween(String value1, String value2) {
            addCriterion("address between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andAddressNotBetween(String value1, String value2) {
            addCriterion("address not between", value1, value2, "address");
            return (Criteria) this;
        }

        public Criteria andHomeIsNull() {
            addCriterion("home is null");
            return (Criteria) this;
        }

        public Criteria andHomeIsNotNull() {
            addCriterion("home is not null");
            return (Criteria) this;
        }

        public Criteria andHomeEqualTo(String value) {
            addCriterion("home =", value, "home");
            return (Criteria) this;
        }

        public Criteria andHomeNotEqualTo(String value) {
            addCriterion("home <>", value, "home");
            return (Criteria) this;
        }

        public Criteria andHomeGreaterThan(String value) {
            addCriterion("home >", value, "home");
            return (Criteria) this;
        }

        public Criteria andHomeGreaterThanOrEqualTo(String value) {
            addCriterion("home >=", value, "home");
            return (Criteria) this;
        }

        public Criteria andHomeLessThan(String value) {
            addCriterion("home <", value, "home");
            return (Criteria) this;
        }

        public Criteria andHomeLessThanOrEqualTo(String value) {
            addCriterion("home <=", value, "home");
            return (Criteria) this;
        }

        public Criteria andHomeLike(String value) {
            addCriterion("home like", value, "home");
            return (Criteria) this;
        }

        public Criteria andHomeNotLike(String value) {
            addCriterion("home not like", value, "home");
            return (Criteria) this;
        }

        public Criteria andHomeIn(List<String> values) {
            addCriterion("home in", values, "home");
            return (Criteria) this;
        }

        public Criteria andHomeNotIn(List<String> values) {
            addCriterion("home not in", values, "home");
            return (Criteria) this;
        }

        public Criteria andHomeBetween(String value1, String value2) {
            addCriterion("home between", value1, value2, "home");
            return (Criteria) this;
        }

        public Criteria andHomeNotBetween(String value1, String value2) {
            addCriterion("home not between", value1, value2, "home");
            return (Criteria) this;
        }

        public Criteria andHeightIsNull() {
            addCriterion("height is null");
            return (Criteria) this;
        }

        public Criteria andHeightIsNotNull() {
            addCriterion("height is not null");
            return (Criteria) this;
        }

        public Criteria andHeightEqualTo(String value) {
            addCriterion("height =", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotEqualTo(String value) {
            addCriterion("height <>", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThan(String value) {
            addCriterion("height >", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightGreaterThanOrEqualTo(String value) {
            addCriterion("height >=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThan(String value) {
            addCriterion("height <", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLessThanOrEqualTo(String value) {
            addCriterion("height <=", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightLike(String value) {
            addCriterion("height like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotLike(String value) {
            addCriterion("height not like", value, "height");
            return (Criteria) this;
        }

        public Criteria andHeightIn(List<String> values) {
            addCriterion("height in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotIn(List<String> values) {
            addCriterion("height not in", values, "height");
            return (Criteria) this;
        }

        public Criteria andHeightBetween(String value1, String value2) {
            addCriterion("height between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHeightNotBetween(String value1, String value2) {
            addCriterion("height not between", value1, value2, "height");
            return (Criteria) this;
        }

        public Criteria andHistoryIsNull() {
            addCriterion("history is null");
            return (Criteria) this;
        }

        public Criteria andHistoryIsNotNull() {
            addCriterion("history is not null");
            return (Criteria) this;
        }

        public Criteria andHistoryEqualTo(String value) {
            addCriterion("history =", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryNotEqualTo(String value) {
            addCriterion("history <>", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryGreaterThan(String value) {
            addCriterion("history >", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryGreaterThanOrEqualTo(String value) {
            addCriterion("history >=", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryLessThan(String value) {
            addCriterion("history <", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryLessThanOrEqualTo(String value) {
            addCriterion("history <=", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryLike(String value) {
            addCriterion("history like", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryNotLike(String value) {
            addCriterion("history not like", value, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryIn(List<String> values) {
            addCriterion("history in", values, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryNotIn(List<String> values) {
            addCriterion("history not in", values, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryBetween(String value1, String value2) {
            addCriterion("history between", value1, value2, "history");
            return (Criteria) this;
        }

        public Criteria andHistoryNotBetween(String value1, String value2) {
            addCriterion("history not between", value1, value2, "history");
            return (Criteria) this;
        }

        public Criteria andAllergicIsNull() {
            addCriterion("allergic is null");
            return (Criteria) this;
        }

        public Criteria andAllergicIsNotNull() {
            addCriterion("allergic is not null");
            return (Criteria) this;
        }

        public Criteria andAllergicEqualTo(String value) {
            addCriterion("allergic =", value, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicNotEqualTo(String value) {
            addCriterion("allergic <>", value, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicGreaterThan(String value) {
            addCriterion("allergic >", value, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicGreaterThanOrEqualTo(String value) {
            addCriterion("allergic >=", value, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicLessThan(String value) {
            addCriterion("allergic <", value, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicLessThanOrEqualTo(String value) {
            addCriterion("allergic <=", value, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicLike(String value) {
            addCriterion("allergic like", value, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicNotLike(String value) {
            addCriterion("allergic not like", value, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicIn(List<String> values) {
            addCriterion("allergic in", values, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicNotIn(List<String> values) {
            addCriterion("allergic not in", values, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicBetween(String value1, String value2) {
            addCriterion("allergic between", value1, value2, "allergic");
            return (Criteria) this;
        }

        public Criteria andAllergicNotBetween(String value1, String value2) {
            addCriterion("allergic not between", value1, value2, "allergic");
            return (Criteria) this;
        }

        public Criteria andFamilyIsNull() {
            addCriterion("family is null");
            return (Criteria) this;
        }

        public Criteria andFamilyIsNotNull() {
            addCriterion("family is not null");
            return (Criteria) this;
        }

        public Criteria andFamilyEqualTo(String value) {
            addCriterion("family =", value, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyNotEqualTo(String value) {
            addCriterion("family <>", value, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyGreaterThan(String value) {
            addCriterion("family >", value, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyGreaterThanOrEqualTo(String value) {
            addCriterion("family >=", value, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyLessThan(String value) {
            addCriterion("family <", value, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyLessThanOrEqualTo(String value) {
            addCriterion("family <=", value, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyLike(String value) {
            addCriterion("family like", value, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyNotLike(String value) {
            addCriterion("family not like", value, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyIn(List<String> values) {
            addCriterion("family in", values, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyNotIn(List<String> values) {
            addCriterion("family not in", values, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyBetween(String value1, String value2) {
            addCriterion("family between", value1, value2, "family");
            return (Criteria) this;
        }

        public Criteria andFamilyNotBetween(String value1, String value2) {
            addCriterion("family not between", value1, value2, "family");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andDelflagIsNull() {
            addCriterion("delflag is null");
            return (Criteria) this;
        }

        public Criteria andDelflagIsNotNull() {
            addCriterion("delflag is not null");
            return (Criteria) this;
        }

        public Criteria andDelflagEqualTo(Boolean value) {
            addCriterion("delflag =", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotEqualTo(Boolean value) {
            addCriterion("delflag <>", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagGreaterThan(Boolean value) {
            addCriterion("delflag >", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagGreaterThanOrEqualTo(Boolean value) {
            addCriterion("delflag >=", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagLessThan(Boolean value) {
            addCriterion("delflag <", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagLessThanOrEqualTo(Boolean value) {
            addCriterion("delflag <=", value, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagIn(List<Boolean> values) {
            addCriterion("delflag in", values, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotIn(List<Boolean> values) {
            addCriterion("delflag not in", values, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagBetween(Boolean value1, Boolean value2) {
            addCriterion("delflag between", value1, value2, "delflag");
            return (Criteria) this;
        }

        public Criteria andDelflagNotBetween(Boolean value1, Boolean value2) {
            addCriterion("delflag not between", value1, value2, "delflag");
            return (Criteria) this;
        }

        public Criteria andClient_idIsNull() {
            addCriterion("client_id is null");
            return (Criteria) this;
        }

        public Criteria andClient_idIsNotNull() {
            addCriterion("client_id is not null");
            return (Criteria) this;
        }

        public Criteria andClient_idEqualTo(Integer value) {
            addCriterion("client_id =", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotEqualTo(Integer value) {
            addCriterion("client_id <>", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idGreaterThan(Integer value) {
            addCriterion("client_id >", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idGreaterThanOrEqualTo(Integer value) {
            addCriterion("client_id >=", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLessThan(Integer value) {
            addCriterion("client_id <", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idLessThanOrEqualTo(Integer value) {
            addCriterion("client_id <=", value, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idIn(List<Integer> values) {
            addCriterion("client_id in", values, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotIn(List<Integer> values) {
            addCriterion("client_id not in", values, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idBetween(Integer value1, Integer value2) {
            addCriterion("client_id between", value1, value2, "client_id");
            return (Criteria) this;
        }

        public Criteria andClient_idNotBetween(Integer value1, Integer value2) {
            addCriterion("client_id not between", value1, value2, "client_id");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table members_info
     *
     * @mbg.generated do_not_delete_during_merge Tue Jul 18 05:12:00 CST 2017
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}