package zdfs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.model.DepartmentT;
import zdfs.model.DepartmentTExample;

public interface DepartmentTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    long countByExample(DepartmentTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int deleteByExample(DepartmentTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int insert(DepartmentT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int insertSelective(DepartmentT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    List<DepartmentT> selectByExample(DepartmentTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    DepartmentT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") DepartmentT record, @Param("example") DepartmentTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int updateByExample(@Param("record") DepartmentT record, @Param("example") DepartmentTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int updateByPrimaryKeySelective(DepartmentT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table department_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int updateByPrimaryKey(DepartmentT record);
}