package zdfs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.model.MetaDoctorTypeT;
import zdfs.model.MetaDoctorTypeTExample;

public interface MetaDoctorTypeTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    long countByExample(MetaDoctorTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int deleteByExample(MetaDoctorTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int insert(MetaDoctorTypeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int insertSelective(MetaDoctorTypeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    List<MetaDoctorTypeT> selectByExample(MetaDoctorTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    MetaDoctorTypeT selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") MetaDoctorTypeT record, @Param("example") MetaDoctorTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int updateByExample(@Param("record") MetaDoctorTypeT record, @Param("example") MetaDoctorTypeTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int updateByPrimaryKeySelective(MetaDoctorTypeT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table meta_doctor_type_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int updateByPrimaryKey(MetaDoctorTypeT record);
}