package zdfs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;

import zdfs.model.DoctorT;
import zdfs.model.PatientT;
import zdfs.model.PatientTExample;

public interface PatientTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Sun Jul 16 13:20:45 CST 2017
     */
    long countByExample(PatientTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Sun Jul 16 13:20:45 CST 2017
     */
    int deleteByExample(PatientTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Sun Jul 16 13:20:45 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Sun Jul 16 13:20:45 CST 2017
     */
    int insert(PatientT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Sun Jul 16 13:20:45 CST 2017
     */
    int insertSelective(PatientT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Sun Jul 16 13:20:45 CST 2017
     */
    List<PatientT> selectByExample(PatientTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Sun Jul 16 13:20:45 CST 2017
     */
    int updateByExampleSelective(@Param("record") PatientT record, @Param("example") PatientTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table patient_t
     *
     * @mbg.generated Sun Jul 16 13:20:45 CST 2017
     */
    int updateByExample(@Param("record") PatientT record, @Param("example") PatientTExample example);

    List<PatientT> selectByDoctorId(@Param("doctorId") int doctorId);
    
}