package zdfs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.model.RDoctorPatientsT;
import zdfs.model.RDoctorPatientsTExample;

public interface RDoctorPatientsTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_patients_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    long countByExample(RDoctorPatientsTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_patients_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    int deleteByExample(RDoctorPatientsTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_patients_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    int insert(RDoctorPatientsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_patients_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    int insertSelective(RDoctorPatientsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_patients_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    List<RDoctorPatientsT> selectByExample(RDoctorPatientsTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_patients_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") RDoctorPatientsT record, @Param("example") RDoctorPatientsTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_patients_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    int updateByExample(@Param("record") RDoctorPatientsT record, @Param("example") RDoctorPatientsTExample example);
}