package zdfs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.model.RDoctorAnychatT;
import zdfs.model.RDoctorAnychatTExample;

public interface RDoctorAnychatTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_anychat_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    long countByExample(RDoctorAnychatTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_anychat_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int deleteByExample(RDoctorAnychatTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_anychat_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int insert(RDoctorAnychatT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_anychat_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int insertSelective(RDoctorAnychatT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_anychat_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    List<RDoctorAnychatT> selectByExample(RDoctorAnychatTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_anychat_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int updateByExampleSelective(@Param("record") RDoctorAnychatT record, @Param("example") RDoctorAnychatTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_doctor_anychat_t
     *
     * @mbg.generated Mon Jul 17 17:25:09 CST 2017
     */
    int updateByExample(@Param("record") RDoctorAnychatT record, @Param("example") RDoctorAnychatTExample example);
}