package zdfs.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.model.RPatientDoctorsT;
import zdfs.model.RPatientDoctorsTExample;

public interface RPatientDoctorsTMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_patient_doctors_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    long countByExample(RPatientDoctorsTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_patient_doctors_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    int deleteByExample(RPatientDoctorsTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_patient_doctors_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    int insert(RPatientDoctorsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_patient_doctors_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    int insertSelective(RPatientDoctorsT record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_patient_doctors_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    List<RPatientDoctorsT> selectByExample(RPatientDoctorsTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_patient_doctors_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    int updateByExampleSelective(@Param("record") RPatientDoctorsT record, @Param("example") RPatientDoctorsTExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table r_patient_doctors_t
     *
     * @mbg.generated Sun Jul 16 22:04:05 CST 2017
     */
    int updateByExample(@Param("record") RPatientDoctorsT record, @Param("example") RPatientDoctorsTExample example);
}