package zdfs.tf02.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.tf02.model.BpData;
import zdfs.tf02.model.BpDataExample;

public interface BpDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    long countByExample(BpDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    int deleteByExample(BpDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    int insert(BpData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    int insertSelective(BpData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    List<BpData> selectByExample(BpDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    BpData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    int updateByExampleSelective(@Param("record") BpData record, @Param("example") BpDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    int updateByExample(@Param("record") BpData record, @Param("example") BpDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    int updateByPrimaryKeySelective(BpData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table bp_data
     *
     * @mbg.generated Tue Jul 18 05:07:32 CST 2017
     */
    int updateByPrimaryKey(BpData record);
    
    
    BpData findLatest(Integer memberId);
}