package zdfs.tf02.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.tf02.model.EcgData;
import zdfs.tf02.model.EcgDataExample;

public interface EcgDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    long countByExample(EcgDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int deleteByExample(EcgDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int insert(EcgData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int insertSelective(EcgData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    List<EcgData> selectByExample(EcgDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    EcgData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") EcgData record, @Param("example") EcgDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByExample(@Param("record") EcgData record, @Param("example") EcgDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByPrimaryKeySelective(EcgData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ecg_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByPrimaryKey(EcgData record);
    
    EcgData findLatest(Integer memberId);
}