package zdfs.tf02.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.tf02.model.GluData;
import zdfs.tf02.model.GluDataExample;

public interface GluDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    long countByExample(GluDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int deleteByExample(GluDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int insert(GluData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int insertSelective(GluData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    List<GluData> selectByExample(GluDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    GluData selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") GluData record, @Param("example") GluDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByExample(@Param("record") GluData record, @Param("example") GluDataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByPrimaryKeySelective(GluData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table glu_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByPrimaryKey(GluData record);
    
    GluData findLatest(int memberId);
}