package zdfs.tf02.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.tf02.model.MembersInfo;
import zdfs.tf02.model.MembersInfoExample;

public interface MembersInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    long countByExample(MembersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int deleteByExample(MembersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int insert(MembersInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int insertSelective(MembersInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    List<MembersInfo> selectByExample(MembersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    MembersInfo selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") MembersInfo record, @Param("example") MembersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByExample(@Param("record") MembersInfo record, @Param("example") MembersInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByPrimaryKeySelective(MembersInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table members_info
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByPrimaryKey(MembersInfo record);
}