package zdfs.tf02.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.tf02.model.Rspo2Data;
import zdfs.tf02.model.Rspo2DataExample;

public interface Rspo2DataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    long countByExample(Rspo2DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int deleteByExample(Rspo2DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int insert(Rspo2Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int insertSelective(Rspo2Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    List<Rspo2Data> selectByExample(Rspo2DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    Rspo2Data selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByExampleSelective(@Param("record") Rspo2Data record, @Param("example") Rspo2DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByExample(@Param("record") Rspo2Data record, @Param("example") Rspo2DataExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByPrimaryKeySelective(Rspo2Data record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table rspo2_data
     *
     * @mbg.generated Tue Jul 18 05:12:00 CST 2017
     */
    int updateByPrimaryKey(Rspo2Data record);
    
    Rspo2Data findLatest(int memberId);
}