package zdfs.tf02.dao;

import java.util.List;
import org.apache.ibatis.annotations.Param;
import zdfs.tf02.model.TodayRemind;
import zdfs.tf02.model.TodayRemindExample;

public interface TodayRemindMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    long countByExample(TodayRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    int deleteByExample(TodayRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    int insert(TodayRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    int insertSelective(TodayRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    List<TodayRemind> selectByExample(TodayRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    TodayRemind selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    int updateByExampleSelective(@Param("record") TodayRemind record, @Param("example") TodayRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    int updateByExample(@Param("record") TodayRemind record, @Param("example") TodayRemindExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    int updateByPrimaryKeySelective(TodayRemind record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table today_remind
     *
     * @mbg.generated Fri Jul 21 03:08:55 CST 2017
     */
    int updateByPrimaryKey(TodayRemind record);
}